// webui/frontend/src-vue/pages/GroupSwitchesPage.vue
<template>
  <div class="page-stack">
    <PageHeader
      index="群开关"
      title="群功能开关"
      description="按页读取本地群目录，明确显示群头像、群号、群名、配置来源与启用状态。未确认群候选默认不进入列表。"
    >
      <template #actions>
        <div class="search-field">
          <input
            v-model="searchDraft"
            placeholder="搜索群号或群名"
            aria-label="搜索群号或群名"
            @input="handleSearchInput"
          />
        </div>
      </template>
    </PageHeader>

    <Panel eyebrow="FILTER / GROUP SWITCHES" title="开关筛选">
      <div class="inline-controls filter-control-row">
        <select :value="enabled" aria-label="按启用状态筛选" @change="onEnabledChange">
          <option value="">全部状态</option>
          <option value="true">仅已启用</option>
          <option value="false">仅已停用</option>
        </select>
        <StateBadge tone="unknown">当前 Bot {{ botStore.selectedBotId || "全部" }}</StateBadge>
        <span v-if="query.data.value">
          启用 {{ query.data.value.enabled_total }} / 停用 {{ query.data.value.disabled_total }}
        </span>
      </div>
    </Panel>

    <QueryBoundary :pending="query.isPending.value" :error="query.error.value">
      <Panel
        v-if="query.data.value?.items?.length"
        eyebrow="GROUPS / SWITCHES"
        :title="`群开关（本页 ${query.data.value.items.length} 项）`"
      >
        <div class="trace-table-wrap">
          <table class="forensic-table">
            <thead>
              <tr>
                <th>群</th>
                <th>群号</th>
                <th>状态</th>
                <th>来源</th>
                <th>关系</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in query.data.value.items" :key="item.group_id">
                <td>
                  <div class="table-identity">
                    <span class="avatar-stamp">
                      <img
                        v-if="item.avatar_url"
                        :src="item.avatar_url"
                        :alt="item.group_name || item.group_id"
                        referrerpolicy="no-referrer"
                      />
                      <span v-else>{{ (item.group_name || item.group_id).slice(0, 1) }}</span>
                    </span>
                    <strong>{{ item.group_name || "未缓存群名" }}</strong>
                  </div>
                </td>
                <td><code>{{ item.group_id }}</code></td>
                <td>
                  <StateBadge :tone="item.enabled ? 'ok' : 'error'">
                    {{ item.enabled ? "启用" : "停用" }}
                  </StateBadge>
                </td>
                <td>
                  <StateBadge tone="unknown" :raw="item.source">
                    {{ sourceLabel(item.source) }}
                  </StateBadge>
                  <small v-if="item.static_config_readonly"> 静态项由群配置覆盖</small>
                </td>
                <td>
                  <StateBadge :tone="item.membership_state === 'confirmed' ? 'ok' : 'unknown'">
                    {{ item.membership_state === "confirmed" ? "已确认" : "已配置" }}
                  </StateBadge>
                </td>
                <td>
                  <button
                    :class="item.enabled ? 'button button-danger' : 'button'"
                    type="button"
                    :disabled="pendingGroupId === item.group_id"
                    @click="requestChange(item)"
                  >
                    {{ pendingGroupId === item.group_id ? "保存并核对…" : item.enabled ? "停用" : "启用" }}
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </Panel>
      <Panel v-else eyebrow="EMPTY" title="暂无数据">
        <p class="muted-copy">当前筛选条件下没有已确认或已配置的群。</p>
      </Panel>
    </QueryBoundary>

    <div v-if="query.data.value && query.data.value.total_pages > 1" class="pagination">
      <button type="button" :disabled="page <= 1" @click="setPage(page - 1)">上一页</button>
      <span>第 {{ query.data.value.page }} / {{ query.data.value.total_pages }} 页（共 {{ query.data.value.total }} 条）</span>
      <button type="button" :disabled="page >= query.data.value.total_pages" @click="setPage(page + 1)">下一页</button>
    </div>

    <Panel v-if="lastDiagnostic" eyebrow="DIAGNOSTIC / RESULT" :title="lastDiagnostic.title || '操作结果'">
      <div class="diagnostic-summary">
        <StateBadge :tone="lastDiagnostic.ok ? 'ok' : 'error'">{{ lastDiagnostic.ok ? "成功" : "失败" }}</StateBadge>
        <span><code>{{ lastDiagnostic.code }}</code> {{ lastDiagnostic.message }}</span>
      </div>
    </Panel>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { useRoute, useRouter } from "vue-router";

import { resources } from "@/api/resources";
import { diagnosticFromError } from "@/api/diagnostics";
import type { GroupSwitchItem, OperationDiagnostic } from "@/api/types";
import PageHeader from "@vue-app/components/PageHeader.vue";
import Panel from "@vue-app/components/Panel.vue";
import QueryBoundary from "@vue-app/components/QueryBoundary.vue";
import StateBadge from "@vue-app/components/StateBadge.vue";
import { useBotStore } from "@vue-app/stores/bot";

const route = useRoute();
const router = useRouter();
const botStore = useBotStore();
const queryClient = useQueryClient();

const page = computed(() => Math.max(1, Number(route.query.page ?? 1) || 1));
const search = computed(() => String(route.query.search ?? ""));
const enabled = computed(() => String(route.query.enabled ?? ""));

const searchDraft = ref(search.value);
watch(search, (next) => { searchDraft.value = next; });

let debounceTimer: ReturnType<typeof setTimeout> | undefined;
function handleSearchInput() {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    const nextQuery = { ...route.query, search: searchDraft.value || undefined, page: "1" };
    router.replace({ query: nextQuery });
  }, 300);
}

function onEnabledChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value;
  router.replace({ query: { ...route.query, enabled: value || undefined, page: "1" } });
}

function setPage(target: number) {
  router.replace({ query: { ...route.query, page: String(target) } });
}

function sourceLabel(value: GroupSwitchItem["source"]): string {
  if (value === "group_config") return "群配置";
  if (value === "config_file") return "静态配置";
  if (value === "dynamic") return "动态白名单";
  return "未配置";
}

const pendingGroupId = ref("");
const lastDiagnostic = ref<OperationDiagnostic | null>(null);

const query = useQuery({
  queryKey: computed(() => ["group-switches", page.value, search.value, enabled.value, botStore.selectedBotId]),
  queryFn: ({ signal }) => resources.groupSwitches(page.value, 20, { search: search.value, enabled: enabled.value, bot_id: botStore.selectedBotId }, signal),
});

const switchMutation = useMutation({
  mutationFn: ({ groupId, target }: { groupId: string; target: boolean }) => resources.updateGroupSwitch(groupId, target),
  onMutate: ({ groupId }) => { pendingGroupId.value = groupId; },
  onSuccess: (diagnostic) => {
    lastDiagnostic.value = diagnostic;
    void queryClient.invalidateQueries({ queryKey: ["group-switches"] });
  },
  onError: (error) => {
    lastDiagnostic.value = diagnosticFromError(error);
  },
  onSettled: () => { pendingGroupId.value = ""; },
});

function requestChange(item: GroupSwitchItem) {
  const target = !item.enabled;
  const action = target ? "启用" : "停用";
  if (!window.confirm(`确认${action}群 ${item.group_name || item.group_id}（${item.group_id}）？\n操作将写入 group_config.enabled，并在保存后重新读取确认。`)) return;
  switchMutation.mutate({ groupId: item.group_id, target });
}
</script>

// webui/frontend/src/pages/GroupSwitchesPage.tsx
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";

import { diagnosticFromError } from "../api/diagnostics";
import { resources } from "../api/resources";
import type { GroupSwitchItem } from "../api/types";
import { useBot } from "../app/BotContext";
import { DiagnosticPanel, useDiagnosticHistory } from "../components/DiagnosticPanel";
import { IdentityAvatar } from "../components/IdentityAvatar";
import { EmptyState, PageHeader, Panel } from "../components/Panel";
import { Pagination } from "../components/Pagination";
import { QueryBoundary } from "../components/QueryBoundary";
import { SearchField } from "../components/SearchField";
import { StateBadge } from "../components/StateBadge";

function sourceLabel(value: GroupSwitchItem["source"]): string {
  return value === "group_config" ? "群配置" : value === "config_file" ? "静态配置" : value === "dynamic" ? "动态白名单" : "未配置";
}

export function GroupSwitchesPage() {
  const { botId } = useBot();
  const [params, setParams] = useSearchParams();
  const page = Math.max(1, Number(params.get("page") ?? 1) || 1);
  const search = params.get("search") ?? "";
  const enabled = params.get("enabled") ?? "";
  const [pendingGroup, setPendingGroup] = useState("");
  const history = useDiagnosticHistory("group-switches");
  const queryClient = useQueryClient();
  const setFilter = (key: string, value: string) => {
    const next = new URLSearchParams(params);
    if (value) next.set(key, value); else next.delete(key);
    if (key !== "page") next.set("page", "1");
    setParams(next);
  };
  const query = useQuery({ queryKey: ["group-switches", page, search, enabled, botId], queryFn: ({ signal }) => resources.groupSwitches(page, 20, { search, enabled, bot_id: botId }, signal), placeholderData: (previous) => previous });
  const update = useMutation({
    mutationFn: ({ groupId, target }: { groupId: string; target: boolean }) => resources.updateGroupSwitch(groupId, target),
    onMutate: ({ groupId }) => setPendingGroup(groupId),
    onSuccess: (diagnostic) => { history.record(diagnostic); void queryClient.invalidateQueries({ queryKey: ["group-switches"] }); },
    onError: (error) => history.record(diagnosticFromError(error)),
    onSettled: () => setPendingGroup(""),
  });
  const requestChange = (item: GroupSwitchItem) => {
    const target = !item.enabled;
    const action = target ? "启用" : "停用";
    if (!window.confirm(`确认${action}群 ${item.group_name || item.group_id}（${item.group_id}）？\n操作将写入 group_config.enabled，并在保存后重新读取确认。`)) return;
    update.mutate({ groupId: item.group_id, target });
  };

  return <div className="page-stack">
    <PageHeader index="群开关" title="群功能开关" description="按页读取本地群目录，明确显示群头像、群号、群名、配置来源与启用状态。未确认群候选默认不进入列表。" actions={<SearchField value={search} onChange={(value) => setFilter("search", value)} placeholder="搜索群号或群名" />} />
    <Panel eyebrow="FILTER / GROUP SWITCHES" title="开关筛选"><div className="inline-controls filter-control-row"><select value={enabled} onChange={(event) => setFilter("enabled", event.target.value)} aria-label="按启用状态筛选"><option value="">全部状态</option><option value="true">仅已启用</option><option value="false">仅已停用</option></select><StateBadge tone="info">当前 Bot {botId || "全部"}</StateBadge>{query.data && <span>启用 {query.data.enabled_total} / 停用 {query.data.disabled_total}</span>}</div></Panel>
    <QueryBoundary isPending={query.isPending} error={query.error}>
      {query.data?.items.length ? <Panel eyebrow="GROUPS / SWITCHES" title={`群开关（本页 ${query.data.items.length} 项）`}><div className="trace-table-wrap"><table className="forensic-table"><thead><tr><th>群</th><th>群号</th><th>状态</th><th>来源</th><th>关系</th><th>操作</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.group_id}><td><div className="table-identity"><IdentityAvatar src={item.avatar_url} label={item.group_name || item.group_id} /><strong>{item.group_name || "未缓存群名"}</strong></div></td><td><code>{item.group_id}</code></td><td><StateBadge tone={item.enabled ? "ok" : "error"}>{item.enabled ? "启用" : "停用"}</StateBadge></td><td><StateBadge tone={item.source === "none" ? "unknown" : "info"} raw={item.source}>{sourceLabel(item.source)}</StateBadge>{item.static_config_readonly && <small> 静态项由群配置覆盖</small>}</td><td><StateBadge tone={item.membership_state === "confirmed" ? "ok" : "info"}>{item.membership_state === "confirmed" ? "已确认" : "已配置"}</StateBadge></td><td><button className={item.enabled ? "button button-danger" : "button"} type="button" disabled={pendingGroup === item.group_id} onClick={() => requestChange(item)}>{pendingGroup === item.group_id ? "保存并核对…" : item.enabled ? "停用" : "启用"}</button></td></tr>)}</tbody></table></div></Panel> : <EmptyState code="group_switches_empty">当前筛选条件下没有已确认或已配置的群。</EmptyState>}
    </QueryBoundary>
    {query.data && <Pagination page={query.data.page} totalPages={query.data.total_pages} onChange={(value) => setFilter("page", String(value))} />}
    {history.diagnostics.map((diagnostic, index) => <DiagnosticPanel key={`${diagnostic.code}:${index}`} diagnostic={diagnostic} defaultOpen={index === 0} />)}
  </div>;
}
