// webui/frontend/src-vue/components/DiagnosticPanel.vue
<template>
  <Panel :eyebrow="`DIAGNOSTIC / ${diagnostic.phase ? diagnostic.phase.toUpperCase() : 'UNKNOWN'}`" :title="diagnostic.title || diagnosticCodeLabel(diagnostic.code)">
    <template #actions><StateBadge :tone="tone">{{ statusLabel }}</StateBadge></template>
    <div class="diagnostic-content">
      <p v-if="diagnostic.message" class="diagnostic-message">{{ diagnostic.message }}</p>
      <p v-if="diagnostic.suggestion" class="diagnostic-suggestion">{{ diagnostic.suggestion }}</p>
      <dl class="compact-kv">
        <dt>诊断码</dt><dd><code>{{ diagnostic.code }}</code></dd>
        <template v-if="diagnostic.operation_id"><dt>Operation ID</dt><dd><code>{{ diagnostic.operation_id }}</code></dd></template>
        <template v-if="diagnostic.trace_id"><dt>Trace ID</dt><dd><code>{{ diagnostic.trace_id }}</code></dd></template>
        <dt>可重试</dt><dd>{{ diagnostic.retryable ? "是" : "否" }}</dd>
      </dl>
      <div v-if="diagnostic.warnings?.length" class="diagnostic-warnings">
        <strong>警告</strong><ul><li v-for="(warning, index) in diagnostic.warnings" :key="index">{{ warning }}</li></ul>
      </div>
      <div v-if="diagnostic.steps?.length" class="diagnostic-steps">
        <strong>步骤详情</strong><ol><li v-for="step in diagnostic.steps" :key="step.key"><span>{{ step.label }}（{{ step.status }}）</span><p v-if="step.message">{{ step.message }}</p></li></ol>
      </div>
    </div>
  </Panel>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { diagnosticCodeLabel } from "@/api/diagnostics";
import type { OperationDiagnostic } from "@/api/types";
import Panel from "@vue-app/components/Panel.vue";
import StateBadge from "@vue-app/components/StateBadge.vue";

const props = defineProps<{ diagnostic: OperationDiagnostic; defaultOpen?: boolean }>();
const tone = computed<"ok" | "warn" | "error" | "running" | "unknown">(() => {
  if (props.diagnostic.ok) return "ok";
  if (props.diagnostic.outcome_unknown) return "unknown";
  if (props.diagnostic.partial) return "warn";
  return "error";
});
const statusLabel = computed(() => props.diagnostic.ok ? "正常" : props.diagnostic.outcome_unknown ? "未知结果" : props.diagnostic.partial ? "部分完成" : "失败");
</script>

// webui/frontend/src/components/DiagnosticPanel.tsx
import { useCallback, useEffect, useState } from "react";

import type { OperationDiagnostic } from "../api/types";
import { safeDiagnostic } from "../api/diagnostics";
import { Icon } from "./Icon";

const HISTORY_PREFIX = "personification.console.diagnostics.";

export function useDiagnosticHistory(scope: string): {
  diagnostics: OperationDiagnostic[];
  record: (diagnostic: OperationDiagnostic) => void;
  clear: () => void;
} {
  const key = `${HISTORY_PREFIX}${scope}`;
  const [diagnostics, setDiagnostics] = useState<OperationDiagnostic[]>(() => {
    try {
      const parsed: unknown = JSON.parse(window.sessionStorage.getItem(key) ?? "[]");
      return Array.isArray(parsed) ? parsed.map((item) => safeDiagnostic(item as Partial<OperationDiagnostic>)).slice(0, 12) : [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    try {
      window.sessionStorage.setItem(key, JSON.stringify(diagnostics));
    } catch {
      // 诊断仍保留在当前 React 状态中。
    }
  }, [diagnostics, key]);

  const record = useCallback((diagnostic: OperationDiagnostic) => {
    const safe = safeDiagnostic(diagnostic);
    setDiagnostics((current) => {
      const fingerprint = safe.operation_id || safe.trace_id || `${safe.code}:${safe.phase}:${safe.message}`;
      return [safe, ...current.filter((item) => (item.operation_id || item.trace_id || `${item.code}:${item.phase}:${item.message}`) !== fingerprint)].slice(0, 12);
    });
  }, []);

  const clear = useCallback(() => setDiagnostics([]), []);
  return { diagnostics, record, clear };
}

export function DiagnosticPanel({ diagnostic, defaultOpen = false }: { diagnostic: OperationDiagnostic; defaultOpen?: boolean }) {
  const tone = diagnostic.ok ? "ok" : diagnostic.outcome_unknown ? "unknown" : "error";
  return (
    <details className={`diagnostic-panel diagnostic-${tone}`} open={defaultOpen}>
      <summary>
        <span className="diagnostic-icon" aria-hidden="true">
          <Icon name={diagnostic.ok ? "check" : diagnostic.outcome_unknown ? "unknown" : "close"} />
        </span>
        <span className="diagnostic-title">
          <strong>{diagnostic.title}</strong>
          <small>{diagnostic.phase}</small>
        </span>
        <code className="operation-code">{diagnostic.code}</code>
        <Icon className="diagnostic-chevron" name="chevron" />
      </summary>
      <div className="diagnostic-body">
        <p>{diagnostic.message || "服务端没有提供更多安全说明。"}</p>
        {diagnostic.outcome_unknown && (
          <div className="unknown-warning">
            结果未知：界面不会自动重试。请先人工核对外部系统。
          </div>
        )}
        {diagnostic.steps.length > 0 && (
          <ol className="diagnostic-steps">
            {diagnostic.steps.map((step) => (
              <li key={step.key} data-status={step.status}>
                <strong>{step.label}</strong>
                {step.message && <span>{step.message}</span>}
              </li>
            ))}
          </ol>
        )}
        {diagnostic.suggestion && <p className="diagnostic-suggestion">建议：{diagnostic.suggestion}</p>}
        <dl className="diagnostic-identifiers">
          {diagnostic.operation_id && <><dt>Operation ID</dt><dd><code>{diagnostic.operation_id}</code></dd></>}
          {diagnostic.trace_id && <><dt>Trace ID</dt><dd><code>{diagnostic.trace_id}</code></dd></>}
          <dt>允许直接重试</dt><dd>{diagnostic.retryable ? "是" : "否"}</dd>
        </dl>
      </div>
    </details>
  );
}
